name: Build

on:
  push:
    branches:
      - main
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: sudo make build
      - uses: actions/setup-python@v2
      # - name: Install numpy and pandas
      #   run: pip3 install numpy pandas
      - uses: BSFishy/pip-action@v1
        with:
          packages: |
            numpy
            pandas
      - name: Generate CSV
        run: sudo python generate_csv.py
      - name: Generate Figures
        run: sudo python csv_to_graph.py
      - uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: .
          output_dir: pdfs
          build_html: false
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: pdfs/report.pdf
          tag: latest
          overwrite: true