name: Generate Report

on:
  push:
    branches:
      - main

jobs:
  converttopdf:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install numpy and pandas
        run: pip install numpy pandas
      - name: Generate CSV
        run: sudo make csv
      - name: Generate Figures
        run: sudo make report
      - uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: .
          output_dir: pdfs
          build_html: false
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: pdfs/report.pdf
          tag: latest
          overwrite: true